// This file is generated by test/internal/cmd/generate-gateway-api-consts. DO NOT EDIT.
// Run "go get sigs.k8s.io/gateway-api@VERSION" and run "make generate" to update.

package consts

const (
	GatewayAPIVersion                   = "v1.0.1-0.20240409212030-c57c131b49f8"
	GatewayAPIPackageVersion            = "v1.0.1-0.20240409212030-c57c131b49f8"
	GatewayStandardCRDsKustomizeURL     = "github.com/kubernetes-sigs/gateway-api/config/crd/?ref=v1.0.1-0.20240409212030-c57c131b49f8"
	GatewayExperimentalCRDsKustomizeURL = "github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.0.1-0.20240409212030-c57c131b49f8"
	GatewayRawRepoURL                   = "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.1-0.20240409212030-c57c131b49f8"
)
